
package sinexcel.wsc.soap.ess;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ESSWebServiceCallback", targetNamespace = "http://xmlns.oracle.com/scheduler", wsdlLocation = "https://ehsj-test.fa.ap1.oraclecloud.com/ess/esswebservice?WSDL")
public class ESSWebServiceCallback_Service
    extends Service
{

    private final static URL ESSWEBSERVICECALLBACK_WSDL_LOCATION;
    private final static WebServiceException ESSWEBSERVICECALLBACK_EXCEPTION;
    private final static QName ESSWEBSERVICECALLBACK_QNAME = new QName("http://xmlns.oracle.com/scheduler", "ESSWebServiceCallback");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehsj-test.fa.ap1.oraclecloud.com/ess/esswebservice?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESSWEBSERVICECALLBACK_WSDL_LOCATION = url;
        ESSWEBSERVICECALLBACK_EXCEPTION = e;
    }

    public ESSWebServiceCallback_Service() {
        super(__getWsdlLocation(), ESSWEBSERVICECALLBACK_QNAME);
    }

    public ESSWebServiceCallback_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESSWEBSERVICECALLBACK_QNAME, features);
    }

    public ESSWebServiceCallback_Service(URL wsdlLocation) {
        super(wsdlLocation, ESSWEBSERVICECALLBACK_QNAME);
    }

    public ESSWebServiceCallback_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESSWEBSERVICECALLBACK_QNAME, features);
    }

    public ESSWebServiceCallback_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ESSWebServiceCallback_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ESSWebServiceCallback
     */
    @WebEndpoint(name = "callbackPort")
    public ESSWebServiceCallback getCallbackPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/scheduler", "callbackPort"), ESSWebServiceCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESSWebServiceCallback
     */
    @WebEndpoint(name = "callbackPort")
    public ESSWebServiceCallback getCallbackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/scheduler", "callbackPort"), ESSWebServiceCallback.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESSWEBSERVICECALLBACK_EXCEPTION!= null) {
            throw ESSWEBSERVICECALLBACK_EXCEPTION;
        }
        return ESSWEBSERVICECALLBACK_WSDL_LOCATION;
    }

}
