
package sinexcel.wsc.soap.ess;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ESSWebService", targetNamespace = "http://xmlns.oracle.com/scheduler")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ESSWebService {


    /**
     * 
     * @param jobDefinitionId
     * @param requestedStartTime
     * @param application
     * @param requestParameters
     * @param description
     * @return
     *     returns long
     * @throws NotFoundException_Exception
     * @throws ValidationException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "submitRequest")
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "submitRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitRequest")
    @ResponseWrapper(localName = "submitRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitRequestResponse")
    public long submitRequest(
            @WebParam(name = "description", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String description,
            @WebParam(name = "jobDefinitionId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    MetadataObjectId jobDefinitionId,
            @WebParam(name = "application", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String application,
            @WebParam(name = "requestedStartTime", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    XMLGregorianCalendar requestedStartTime,
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters)
        throws NotFoundException_Exception, RuntimeServiceException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param jobDefinitionId
     * @param requestedStartTime
     * @param requestedEndTime
     * @param application
     * @param triggerId
     * @param requestParameters
     * @param description
     * @param scheduleId
     * @return
     *     returns long
     * @throws NotFoundException_Exception
     * @throws ValidationException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "submitRecurringRequest")
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "submitRecurringRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitRecurringRequest")
    @ResponseWrapper(localName = "submitRecurringRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitRecurringRequestResponse")
    public long submitRecurringRequest(
            @WebParam(name = "description", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String description,
            @WebParam(name = "jobDefinitionId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    MetadataObjectId jobDefinitionId,
            @WebParam(name = "scheduleId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    MetadataObjectId scheduleId,
            @WebParam(name = "triggerId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    MetadataObjectId triggerId,
            @WebParam(name = "application", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String application,
            @WebParam(name = "requestedStartTime", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    XMLGregorianCalendar requestedStartTime,
            @WebParam(name = "requestedEndTime", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    XMLGregorianCalendar requestedEndTime,
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters)
        throws NotFoundException_Exception, RuntimeServiceException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param jobDefinitionId
     * @param requestedStartTime
     * @param requestedEndTime
     * @param application
     * @param iCalSchedule
     * @param requestParameters
     * @param description
     * @return
     *     returns long
     * @throws NotFoundException_Exception
     * @throws NotAllowedException_Exception
     * @throws ValidationException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "submitInstantRecurringRequest")
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "submitInstantRecurringRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitInstantRecurringRequest")
    @ResponseWrapper(localName = "submitInstantRecurringRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SubmitInstantRecurringRequestResponse")
    public long submitInstantRecurringRequest(
            @WebParam(name = "description", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String description,
            @WebParam(name = "jobDefinitionId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    MetadataObjectId jobDefinitionId,
            @WebParam(name = "iCalSchedule", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String iCalSchedule,
            @WebParam(name = "application", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String application,
            @WebParam(name = "requestedStartTime", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    XMLGregorianCalendar requestedStartTime,
            @WebParam(name = "requestedEndTime", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    XMLGregorianCalendar requestedEndTime,
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters)
        throws NotAllowedException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param requestId
     */
    @WebMethod(action = "getCompletionStatus")
    @Oneway
    @RequestWrapper(localName = "getCompletionStatus", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetCompletionStatus")
    public void getCompletionStatus(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId);

    /**
     * 
     * @param requestId
     * @return
     *     returns sinexcel.wsc.soap.ess.State
     * @throws NotFoundException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "getRequestState")
    @WebResult(name = "state", targetNamespace = "")
    @RequestWrapper(localName = "getRequestState", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestState")
    @ResponseWrapper(localName = "getRequestStateResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestStateResponse")
    public State getRequestState(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestExecutionContext
     * @return
     *     returns boolean
     * @throws NotFoundException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "checkInCancelling")
    @WebResult(name = "isCancelling", targetNamespace = "")
    @RequestWrapper(localName = "checkInCancelling", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.CheckInCancelling")
    @ResponseWrapper(localName = "checkInCancellingResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.CheckInCancellingResponse")
    public boolean checkInCancelling(
            @WebParam(name = "requestExecutionContext", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String requestExecutionContext)
        throws NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestDetail
     * @throws NotFoundException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "getRequestDetail")
    @WebResult(name = "requestDetail", targetNamespace = "")
    @RequestWrapper(localName = "getRequestDetail", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestDetail")
    @ResponseWrapper(localName = "getRequestDetailResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestDetailResponse")
    public RequestDetail getRequestDetail(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestExecutionContext
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestExecutionContext
     * @throws NotFoundException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "getRequestExecutionContext")
    @WebResult(name = "requestExecutionContext", targetNamespace = "")
    @RequestWrapper(localName = "getRequestExecutionContext", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestExecutionContext")
    @ResponseWrapper(localName = "getRequestExecutionContextResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.GetRequestExecutionContextResponse")
    public RequestExecutionContext getRequestExecutionContext(
            @WebParam(name = "requestExecutionContext", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String requestExecutionContext)
        throws NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @throws NotAllowedException_Exception
     * @throws NotFoundException_Exception
     * @throws IllegalStateException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "holdRequest")
    @RequestWrapper(localName = "holdRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.HoldRequest")
    @ResponseWrapper(localName = "holdRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.HoldRequestResponse")
    public void holdRequest(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws IllegalStateException_Exception, NotAllowedException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @throws NotFoundException_Exception
     * @throws IllegalStateException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "releaseRequest")
    @RequestWrapper(localName = "releaseRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.ReleaseRequest")
    @ResponseWrapper(localName = "releaseRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.ReleaseRequestResponse")
    public void releaseRequest(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws IllegalStateException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestExecutionContext
     * @param statusMessage
     * @param status
     * @throws RequestNotFoundException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "setAsyncRequestStatus")
    @RequestWrapper(localName = "setAsyncRequestStatus", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetAsyncRequestStatus")
    @ResponseWrapper(localName = "setAsyncRequestStatusResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetAsyncRequestStatusResponse")
    public void setAsyncRequestStatus(
            @WebParam(name = "requestExecutionContext", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String requestExecutionContext,
            @WebParam(name = "status", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    AsyncStatus status,
            @WebParam(name = "statusMessage", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    String statusMessage)
        throws RequestNotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @throws NotFoundException_Exception
     * @throws IllegalStateException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "cancelRequest")
    @RequestWrapper(localName = "cancelRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.CancelRequest")
    @ResponseWrapper(localName = "cancelRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.CancelRequestResponse")
    public void cancelRequest(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws IllegalStateException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @throws NotAllowedException_Exception
     * @throws NotFoundException_Exception
     * @throws IllegalStateException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "deleteRequest")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.DeleteRequestResponse")
    public void deleteRequest(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws IllegalStateException_Exception, NotAllowedException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestId
     * @throws NotFoundException_Exception
     * @throws NotAllowedException_Exception
     * @throws IllegalStateException_Exception
     * @throws RuntimeServiceException_Exception
     */
    @WebMethod(action = "purgeRequest")
    @RequestWrapper(localName = "purgeRequest", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.PurgeRequest")
    @ResponseWrapper(localName = "purgeRequestResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.PurgeRequestResponse")
    public void purgeRequest(
            @WebParam(name = "requestId", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    long requestId)
        throws IllegalStateException_Exception, NotAllowedException_Exception, NotFoundException_Exception, RuntimeServiceException_Exception
    ;

    /**
     * 
     * @param requestParameters
     * @param arguments
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestParameters
     * @throws IllegalArgumentException_Exception
     */
    @WebMethod(action = "setSubmitArgs")
    @WebResult(name = "requestParametersReturn", targetNamespace = "")
    @RequestWrapper(localName = "setSubmitArgs", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetSubmitArgs")
    @ResponseWrapper(localName = "setSubmitArgsResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetSubmitArgsResponse")
    public RequestParameters setSubmitArgs(
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters,
            @WebParam(name = "arguments", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    List<String> arguments)
        throws IllegalArgumentException_Exception
    ;

    /**
     * 
     * @param stepArgsList
     * @param requestParameters
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestParameters
     * @throws IllegalArgumentException_Exception
     */
    @WebMethod(action = "setStepsArgs")
    @WebResult(name = "requestParametersReturn", targetNamespace = "")
    @RequestWrapper(localName = "setStepsArgs", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetStepsArgs")
    @ResponseWrapper(localName = "setStepsArgsResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetStepsArgsResponse")
    public RequestParameters setStepsArgs(
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters,
            @WebParam(name = "stepArgsList", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    List<StepArgs> stepArgsList)
        throws IllegalArgumentException_Exception
    ;

    /**
     * 
     * @param requestParameters
     * @param postProcessActions
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestParameters
     * @throws IllegalArgumentException_Exception
     */
    @WebMethod(action = "addPPActions")
    @WebResult(name = "requestParametersReturn", targetNamespace = "")
    @RequestWrapper(localName = "addPPActions", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.AddPPActions")
    @ResponseWrapper(localName = "addPPActionsResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.AddPPActionsResponse")
    public RequestParameters addPPActions(
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters,
            @WebParam(name = "postProcessActions", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    List<PostProcessAction> postProcessActions)
        throws IllegalArgumentException_Exception
    ;

    /**
     * 
     * @param requestParameters
     * @param nlsOptions
     * @return
     *     returns sinexcel.wsc.soap.ess.RequestParameters
     * @throws IllegalArgumentException_Exception
     */
    @WebMethod(action = "setNLSOptions")
    @WebResult(name = "requestParametersReturn", targetNamespace = "")
    @RequestWrapper(localName = "setNLSOptions", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetNLSOptions")
    @ResponseWrapper(localName = "setNLSOptionsResponse", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.SetNLSOptionsResponse")
    public RequestParameters setNLSOptions(
            @WebParam(name = "requestParameters", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    RequestParameters requestParameters,
            @WebParam(name = "nlsOptions", targetNamespace = "http://xmlns.oracle.com/scheduler")
                    NlsOptions nlsOptions)
        throws IllegalArgumentException_Exception
    ;

}
