
package sinexcel.wsc.soap.ess;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ESSWebServiceCallback", targetNamespace = "http://xmlns.oracle.com/scheduler")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ESSWebServiceCallback {


    /**
     * 
     * @param requestId
     * @param state
     * @param resultMessage
     */
    @WebMethod(action = "onJobCompletion")
    @Oneway
    @RequestWrapper(localName = "onJobCompletion", targetNamespace = "http://xmlns.oracle.com/scheduler", className = "sinexcel.wsc.soap.ess.OnJobCompletion")
    public void onJobCompletion(
            @WebParam(name = "requestId", targetNamespace = "")
                    long requestId,
            @WebParam(name = "state", targetNamespace = "")
                    State state,
            @WebParam(name = "resultMessage", targetNamespace = "")
                    String resultMessage);

}
