
package sinexcel.wsc.soap.ess;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalStateException", targetNamespace = "http://xmlns.oracle.com/scheduler")
public class IllegalStateException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalStateException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IllegalStateException_Exception(String message, IllegalStateException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IllegalStateException_Exception(String message, IllegalStateException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sinexcel.wsc.soap.ess.IllegalStateException
     */
    public IllegalStateException getFaultInfo() {
        return faultInfo;
    }

}
