# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        druid:
            # 主库数据源
            master:
                url: jdbc:sqlserver://218.13.78.50:31433;SelectMethod=cursor;DatabaseName=pes-test
                username: sa
                password: "@Sin86511588"
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:sqlserver://218.13.78.50:21433;SelectMethod=cursor;DatabaseName=OrBitXI
                username: user_001
                password: "user_001"
#        # mes数据源(当前是测试 未连接mes)
#                    mes:
##                        # 从数据源开关/默认关闭
#                        enabled: true
#                        url: jdbc:sqlserver://172.17.101.4:1433; DatabaseName=mes;allowMultiQueries=true
#                        username: sa
#                        password: '@Sinexcel.211122*+-'
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 30
            # 最大连接池数量
            maxActive: 100
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 60000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true