
package sinexcel.wsc.soap.report;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportService", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportService {


//    /**
//     *
//     * @param reportRequest
//     * @param bipSessionToken
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportResponse
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "runReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "runReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunReportInSession")
//    @ResponseWrapper(localName = "runReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunReportInSessionResponse")
//    public ReportResponse runReportInSession(
//        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportRequest reportRequest,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns sinexcel.wsc.soap.report.ReportResponse
     * @throws AccessDeniedException_Exception
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "runDataModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runDataModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunDataModel")
    @ResponseWrapper(localName = "runDataModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunDataModelResponse")
    public ReportResponse runDataModel(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;
//
//    /**
//     *
//     * @param reportRequest
//     * @param bipSessionToken
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportResponse
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "runDataModelInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "runDataModelInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunDataModelInSession")
//    @ResponseWrapper(localName = "runDataModelInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunDataModelInSessionResponse")
//    public ReportResponse runDataModelInSession(
//        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportRequest reportRequest,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportDefinition
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportDefinition")
//    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportDefinitionResponse")
//    public ReportDefinition getReportDefinition(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportDefinition
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportDefinitionInSession")
//    @ResponseWrapper(localName = "getReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportDefinitionInSessionResponse")
//    public ReportDefinition getReportDefinitionInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns sinexcel.wsc.soap.report.MobileAppDefinition
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getMobileAppDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getMobileAppDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetMobileAppDefinition")
//    @ResponseWrapper(localName = "getMobileAppDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetMobileAppDefinitionResponse")
//    public MobileAppDefinition getMobileAppDefinition(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportSampleDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportSampleData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportSampleData")
//    @ResponseWrapper(localName = "getReportSampleDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportSampleDataResponse")
//    public byte[] getReportSampleData(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportSampleDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportSampleDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportSampleDataInSession")
//    @ResponseWrapper(localName = "getReportSampleDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportSampleDataInSessionResponse")
//    public byte[] getReportSampleDataInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param locale
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getXDOSchemaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getXDOSchema", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetXDOSchema")
//    @ResponseWrapper(localName = "getXDOSchemaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetXDOSchemaResponse")
//    public byte[] getXDOSchema(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param locale
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getXDOSchemaInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getXDOSchemaInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetXDOSchemaInSession")
//    @ResponseWrapper(localName = "getXDOSchemaInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetXDOSchemaInSessionResponse")
//    public byte[] getXDOSchemaInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateID
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateAvailableLocalesInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateAvailableLocalesInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableLocalesInSession")
//    @ResponseWrapper(localName = "getTemplateAvailableLocalesInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableLocalesInSessionResponse")
//    public List<String> getTemplateAvailableLocalesInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateAvailableXLIFFsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateAvailableXLIFFs", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableXLIFFs")
//    @ResponseWrapper(localName = "getTemplateAvailableXLIFFsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableXLIFFsResponse")
//    public List<String> getTemplateAvailableXLIFFs(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateID
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateAvailableXLIFFsInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateAvailableXLIFFsInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableXLIFFsInSession")
//    @ResponseWrapper(localName = "getTemplateAvailableXLIFFsInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableXLIFFsInSessionResponse")
//    public List<String> getTemplateAvailableXLIFFsInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateID
//     * @param bipSessionToken
//     * @param locale
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateInSession")
//    @ResponseWrapper(localName = "getTemplateInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateInSessionResponse")
//    public byte[] getTemplateInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param reportRequest
//     * @param bipSessionToken
//     * @return
//     *     returns sinexcel.wsc.soap.report.ParamNameValues
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportParametersInSession")
//    @ResponseWrapper(localName = "getReportParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportParametersInSessionResponse")
//    public ParamNameValues getReportParametersInSession(
//        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportRequest reportRequest,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<sinexcel.wsc.soap.report.ParamNameValue>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateParameters")
//    @ResponseWrapper(localName = "getTemplateParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateParametersResponse")
//    public List<ParamNameValue> getTemplateParameters(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateID
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<sinexcel.wsc.soap.report.ParamNameValue>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateParametersInSession")
//    @ResponseWrapper(localName = "getTemplateParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateParametersInSessionResponse")
//    public List<ParamNameValue> getTemplateParametersInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param connectionName
//     * @param password
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getListOfSubjectAreaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getListOfSubjectArea", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetListOfSubjectArea")
//    @ResponseWrapper(localName = "getListOfSubjectAreaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetListOfSubjectAreaResponse")
//    public List<String> getListOfSubjectArea(
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password,
//        @WebParam(name = "connectionName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String connectionName)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param connectionName
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getListOfSubjectAreaInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getListOfSubjectAreaInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetListOfSubjectAreaInSession")
//    @ResponseWrapper(localName = "getListOfSubjectAreaInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetListOfSubjectAreaInSessionResponse")
//    public List<String> getListOfSubjectAreaInSession(
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken,
//        @WebParam(name = "connectionName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String connectionName)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateFileName
//     * @param folderAbsolutePathURL
//     * @param templateData
//     * @param xliffData
//     * @param xliffFileName
//     * @param bipSessionToken
//     * @param updateFlag
//     * @param reportName
//     * @param dataModelURL
//     * @return
//     *     returns java.lang.String
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "createReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "createReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.CreateReportInSession")
//    @ResponseWrapper(localName = "createReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.CreateReportInSessionResponse")
//    public String createReportInSession(
//        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportName,
//        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String folderAbsolutePathURL,
//        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String dataModelURL,
//        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateFileName,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String xliffFileName,
//        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        boolean updateFlag,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param newReportDefn
//     * @param password
//     * @param reportAbsPath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateReportDefinition")
//    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateReportDefinitionResponse")
//    public boolean updateReportDefinition(
//        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsPath,
//        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportDefinition newReportDefn,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param newReportDefn
//     * @param reportAbsPath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateReportDefinitionInSession")
//    @ResponseWrapper(localName = "updateReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateReportDefinitionInSessionResponse")
//    public boolean updateReportDefinitionInSession(
//        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsPath,
//        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportDefinition newReportDefn,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param objectPath
//     * @param password
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "removeObjectFromCacheReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "removeObjectFromCache", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveObjectFromCache")
//    @ResponseWrapper(localName = "removeObjectFromCacheResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveObjectFromCacheResponse")
//    public boolean removeObjectFromCache(
//        @WebParam(name = "objectPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String objectPath,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param objectPath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "removeObjectFromCacheInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "removeObjectFromCacheInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveObjectFromCacheInSession")
//    @ResponseWrapper(localName = "removeObjectFromCacheInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveObjectFromCacheInSessionResponse")
//    public boolean removeObjectFromCacheInSession(
//        @WebParam(name = "objectPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String objectPath,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param password
//     * @param newMobileAppDefn
//     * @param reportAbsPath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateMobileAppDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateMobileAppDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateMobileAppDefinition")
//    @ResponseWrapper(localName = "updateMobileAppDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateMobileAppDefinitionResponse")
//    public boolean updateMobileAppDefinition(
//        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsPath,
//        @WebParam(name = "newMobileAppDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        MobileAppDefinition newMobileAppDefn,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateType
//     * @param templateData
//     * @param locale
//     * @param password
//     * @param reportAbsolutePath
//     * @param templateName
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadTemplateForReport")
//    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadTemplateForReportResponse")
//    public boolean uploadTemplateForReport(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateName,
//        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateType,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateType
//     * @param templateData
//     * @param bipSessionToken
//     * @param locale
//     * @param reportAbsolutePath
//     * @param templateName
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadTemplateForReportInSession")
//    @ResponseWrapper(localName = "uploadTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadTemplateForReportInSessionResponse")
//    public boolean uploadTemplateForReportInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateName,
//        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateType,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateData
//     * @param locale
//     * @param password
//     * @param reportAbsolutePath
//     * @param templateName
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateTemplateForReport")
//    @ResponseWrapper(localName = "updateTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateTemplateForReportResponse")
//    public boolean updateTemplateForReport(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateData
//     * @param bipSessionToken
//     * @param locale
//     * @param reportAbsolutePath
//     * @param templateName
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateTemplateForReportInSession")
//    @ResponseWrapper(localName = "updateTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateTemplateForReportInSessionResponse")
//    public boolean updateTemplateForReportInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateFileName
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveTemplateForReport")
//    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveTemplateForReportResponse")
//    public boolean removeTemplateForReport(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateFileName,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param templateFileName
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "removeTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "removeTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveTemplateForReportInSession")
//    @ResponseWrapper(localName = "removeTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RemoveTemplateForReportInSessionResponse")
//    public boolean removeTemplateForReportInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateFileName,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param xliffData
//     * @param locale
//     * @param layoutFileName
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadXLIFFForReport")
//    @ResponseWrapper(localName = "uploadXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadXLIFFForReportResponse")
//    public boolean uploadXLIFFForReport(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String layoutFileName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param xliffData
//     * @param bipSessionToken
//     * @param locale
//     * @param layoutFileName
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateXLIFFForReportInSession")
//    @ResponseWrapper(localName = "updateXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateXLIFFForReportInSessionResponse")
//    public boolean updateXLIFFForReportInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String layoutFileName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param xliffData
//     * @param locale
//     * @param layoutFileName
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateXLIFFForReport")
//    @ResponseWrapper(localName = "updateXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateXLIFFForReportResponse")
//    public boolean updateXLIFFForReport(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String layoutFileName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param xliffData
//     * @param bipSessionToken
//     * @param locale
//     * @param layoutFileName
//     * @param reportAbsolutePath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadXLIFFForReportInSession")
//    @ResponseWrapper(localName = "uploadXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadXLIFFForReportInSessionResponse")
//    public boolean uploadXLIFFForReportInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String layoutFileName,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param reportRawDataChunk
//     * @param userID
//     * @param fileID
//     * @param reportDataChunk
//     * @param password
//     * @return
//     *     returns java.lang.String
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadReportDataChunk")
//    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadReportDataChunkResponse")
//    public String uploadReportDataChunk(
//        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String fileID,
//        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] reportDataChunk,
//        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportRawDataChunk,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param reportRawDataChunk
//     * @param fileID
//     * @param bipSessionToken
//     * @param reportDataChunk
//     * @return
//     *     returns java.lang.String
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "uploadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "uploadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadReportDataChunkInSession")
//    @ResponseWrapper(localName = "uploadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UploadReportDataChunkInSessionResponse")
//    public String uploadReportDataChunkInSession(
//        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String fileID,
//        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] reportDataChunk,
//        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportRawDataChunk,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param fileID
//     * @param beginIdx
//     * @param password
//     * @param size
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportDataChunk
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.DownloadReportDataChunk")
//    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.DownloadReportDataChunkResponse")
//    public ReportDataChunk downloadReportDataChunk(
//        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String fileID,
//        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        int beginIdx,
//        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        int size,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param fileID
//     * @param beginIdx
//     * @param bipSessionToken
//     * @param size
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportDataChunk
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "downloadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "downloadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.DownloadReportDataChunkInSession")
//    @ResponseWrapper(localName = "downloadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.DownloadReportDataChunkInSessionResponse")
//    public ReportDataChunk downloadReportDataChunkInSession(
//        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String fileID,
//        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        int beginIdx,
//        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        int size,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateFileName
//     * @param folderAbsolutePathURL
//     * @param templateData
//     * @param xliffData
//     * @param xliffFileName
//     * @param updateFlag
//     * @param password
//     * @param reportName
//     * @param dataModelURL
//     * @return
//     *     returns java.lang.String
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.CreateReport")
//    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.CreateReportResponse")
//    public String createReport(
//        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportName,
//        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String folderAbsolutePathURL,
//        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String dataModelURL,
//        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateFileName,
//        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] templateData,
//        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String xliffFileName,
//        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        byte[] xliffData,
//        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        boolean updateFlag,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param reportAbsolutePath
//     * @return
//     *     returns sinexcel.wsc.soap.report.MobileAppDefinition
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getMobileAppDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getMobileAppDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetMobileAppDefinitionInSession")
//    @ResponseWrapper(localName = "getMobileAppDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetMobileAppDefinitionInSessionResponse")
//    public MobileAppDefinition getMobileAppDefinitionInSession(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param bipSessionToken
//     * @param newMobileAppDefn
//     * @param reportAbsPath
//     * @return
//     *     returns boolean
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "updateMobileAppDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "updateMobileAppDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateMobileAppDefinitionInSession")
//    @ResponseWrapper(localName = "updateMobileAppDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.UpdateMobileAppDefinitionInSessionResponse")
//    public boolean updateMobileAppDefinitionInSession(
//        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsPath,
//        @WebParam(name = "newMobileAppDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        MobileAppDefinition newMobileAppDefn,
//        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String bipSessionToken)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateID
//     * @param locale
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns byte[]
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplate")
//    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateResponse")
//    public byte[] getTemplate(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String locale,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param reportRequest
//     * @param password
//     * @return
//     *     returns sinexcel.wsc.soap.report.ReportResponse
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunReport")
//    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.RunReportResponse")
//    public ReportResponse runReport(
//        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportRequest reportRequest,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param reportRequest
//     * @param password
//     * @return
//     *     returns sinexcel.wsc.soap.report.ParamNameValues
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportParameters")
//    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetReportParametersResponse")
//    public ParamNameValues getReportParameters(
//        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        ReportRequest reportRequest,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;
//
//    /**
//     *
//     * @param userID
//     * @param templateID
//     * @param password
//     * @param reportAbsolutePath
//     * @return
//     *     returns java.util.List<java.lang.String>
//     * @throws AccessDeniedException_Exception
//     * @throws OperationFailedException_Exception
//     * @throws InvalidParametersException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "getTemplateAvailableLocalesReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//    @RequestWrapper(localName = "getTemplateAvailableLocales", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableLocales")
//    @ResponseWrapper(localName = "getTemplateAvailableLocalesResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "sinexcel.wsc.soap.report.GetTemplateAvailableLocalesResponse")
//    public List<String> getTemplateAvailableLocales(
//        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String reportAbsolutePath,
//        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String templateID,
//        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String userID,
//        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
//        String password)
//        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
//    ;

}
